Update Catch2 to v3.4.0
Without upgrading Catch2, The following error occurs when building on
Ubuntu 22.04 due to glibc:

cucim/build-debug/_deps/deps-catch2-src/single_include/catch2/
catch.hpp:10830:58: error: call to non-‘constexpr’ function
‘long int sysconf(int)’
10830 |     static constexpr std::size_t sigStackSize = 32768 >=
                MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;

Signed-off-by: Gigon Bae <gbae@nvidia.com>