Support raw RGB tiled TIFF (#108)
Due to #17 ([BUG] Compression scheme 33003 tile decoding is not implemented), #19 (Check compression method used in the image) was merged so cuCIM has been handling only particular formats (only jpeg/deflate-compressed image).

If the input TIFF image has no-compressed RAW tile image, cuCIM showed the following error message:

> RuntimeError: This format (compression: 1, sample_per_pixel: 1, planar_config: 1, photometric: 1) is not supported yet!. https://github.com/Project-MONAI/MONAI/pull/2987/checks?check_run_id=3667530814#step:7:15641

This patch is to support raw RGB tiled TIFF with fast-path, re-allowing non-compressed image with slow-path (in case the input is not tiled RGB image).

This supports https://github.com/Project-MONAI/MONAI/pull/2987.

Authors:
  - Gigon Bae (https://github.com/gigony)

Approvers:
  - Gregory R. Lee (https://github.com/grlee77)
  - https://github.com/jakirkham

URL: https://github.com/rapidsai/cucim/pull/108