run: fix compatibility with PEP-0632 for supporting Python >=3.12 (#902)
In PEP 632 [1] it is stated that distutils is deprecated in Python 3.10 and 3.11 and will no longer be installed in Python 3.12

run make use of distutils.sysconfig to find the location of the Python .so and include path. PEP 632 recommends replacement with sysconfig.

Today when attempting to build cucim with Python 3.12.3 build_local_cucim_() fails with:

```
+ local build_folder=/cucim/python/build-debug
+ local CMAKE_CMD=cmake
+ pushd /cucim/python
+ local python_library ++ python3 -c 'import distutils.sysconfig as sysconfig, os; print(os.path.join(sysconfig.get_config_var('\''LIBDIR'\''), sysconfig.get_config_var('\''LDLIBRARY'\'')))' Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'distutils'
```


This test was also tested on Python 3.11 for backwards compatibility.

[1] https://peps.python.org/pep-0632/

Authors:
  - Elie De Brauwer (https://github.com/ElieDeBrauwer)
  - Gigon Bae (https://github.com/gigony)

Approvers:
  - https://github.com/jakirkham

URL: https://github.com/rapidsai/cucim/pull/902