Fix primitives benchmark code
Pointer variable is used after releasing the memory with free().
This is a bug and should be fixed.

Without this fix, the benchmark code may not build or run correctly.
  error: pointer used after 'void free(void*)' [-Werror=use-after-free]

This commit fixes the issue by releasing the memory after
benchmark::DoNotOptimize() is called.