update incorrect argument and deprecated function for tifffile.TiffWriter (#433)
1. Both ```tifffile.TiffWriter.write()```[[link](https://github.com/cgohlke/tifffile/blob/master/tifffile/tifffile.py#L1530)] and ```tifffile.TiffWriter.save()```[[link](https://github.com/cgohlke/tifffile/blob/master/tifffile/tifffile.py#L3284)] receive ```compression``` not ```compress```
->  Current version doesn't work and raises the following error msg:
```
tifffile TypeError: write() got an unexpected keyword argument 'compress'
```

3. ```tifffile.TiffWriter.write()``` instead of ```tifffile.TiffWriter.save()```, which has been deprecated [[link](https://github.com/cgohlke/tifffile/blob/master/tifffile/tifffile.py#L3287)]


<!--

Thank you for contributing to cuCIM :)

Here are some guidelines to help the review process go smoothly.

1. Please write a description in this text box of the changes that are being
   made.

2. Please ensure that you have written units tests for the changes made/features
   added.

3. If you are closing an issue please use one of the automatic closing words as
   noted here: https://help.github.com/articles/closing-issues-using-keywords/

4. If your pull request is not ready for review but you want to make use of the
   continuous integration testing facilities please label it with `[WIP]`.

5. If your pull request is ready to be reviewed without requiring additional
   work on top of it, then remove the `[WIP]` label (if present) and replace
   it with `[REVIEW]`. If assistance is required to complete the functionality,
   for example when the C/C++ code of a feature is complete but Python bindings
   are still required, then add the label `[HELP-REQ]` so that others can triage
   and assist. The additional changes then can be implemented on top of the
   same PR. If the assistance is done by members of the rapidsAI team, then no
   additional actions are required by the creator of the original PR for this,
   otherwise the original author of the PR needs to give permission to the
   person(s) assisting to commit to their personal fork of the project. If that
   doesn't happen then a new PR based on the code of the original PR can be
   opened by the person assisting, which then will be the PR that will be
   merged.

6. Once all work has been done and review has taken place please do not add
   features or make changes out of the scope of those requested by the reviewer
   (doing this just add delays as already reviewed code ends up having to be
   re-reviewed/it is hard to tell what is new etc!). Further, please do not
   rebase your branch on main/force push/rewrite history, doing any of these
   causes the context of any comments made by reviewers to be lost. If
   conflicts occur against main they should be resolved by merging main
   into the branch used for making the pull request.

Many thanks in advance for your cooperation!

-->

Authors:
  - https://github.com/JoohyungLee0106
  - Gigon Bae (https://github.com/gigony)
  - Gregory Lee (https://github.com/grlee77)

Approvers:
  - Gregory Lee (https://github.com/grlee77)
  - AJ Schmidt (https://github.com/ajschmidt8)

URL: https://github.com/rapidsai/cucim/pull/433